# Author: Aris Christoforidis

# EVOLUTION
POPULATION_SIZE = 1
GENERATIONS = 10
MAX_NOTABLE_MODULES = 100
TEMP_MODULE_TTL = 20
MIN_PROPERTIES_OBS_COUNT = 5
LAYERS_LIST = ['CONV_1.H', 'CONV_2.H', 'CONV_3.H', 'POOL_2.A', 'POOL_3.A', 'POOL_5.A',
               'CONV_1.N', 'CONV_2.N', 'CONV_3.N', 'POOL_2.M', 'POOL_3.M', 'POOL_5.M']

# GRAPH
NODE_INTERNAL_COUNT_RANGE = range(2,3)
NODE_INPUT_TAG = 'INPUT'
NODE_OUTPUT_TAG = 'OUTPUT'
MAX_NODES = 7
MAX_EDGES = 9
LAYER_INPUT_PREFIX = 'IN'
LAYER_OUTPUT_SUFFIX = 'OUT'


# PROBABILITY
DROPOUT_PROBABILITY = 0.1

# DATA
DATASET = 'activity_recognition'

# LAYERS
CHANNEL_COUNT = 32
STRIDE_COUNT = 1

# EVALUATION
UNEVALUATED_FITNESS = -1
METRIC = 'acc'
EPOCHS = 10
